export const courses = [
  {
    slug: 'introduction-to-programmable-controllers',
    title: 'Introduction to Programmable Controllers',
    level: 'Intro',
    category: 'PLC Fundamentals',
    platform: 'Siemens PLC Concepts',
    duration: '5 days',
    prerequisites: 'Basic electrical knowledge recommended',
    summary: 'Master the fundamentals of Programmable Logic Controllers. Learn basic PLC concepts, wiring practices, digital logic, and introductory troubleshooting techniques.',
    who_its_for: 'This course is ideal for electrical technicians, maintenance personnel, and engineering students who are new to PLCs and want to build a solid foundation in automation fundamentals.',
    outcomes: ["Understand what a PLC is, where it\'s used, and how the scan cycle works","Apply basic safety principles and good wiring practices","Implement AND/OR/NOT logic, latching, and interlocks","Use timers and counters for basic control applications","Read and create basic tag documentation","Identify common wiring and logic mistakes"],
    syllabus: [{section: 'PLC Fundamentals',topics: ["What a PLC is, where it\'s used, scan cycle, I/O concepts","Safety basics and good wiring practices"]},{section: 'Basic Logic',topics: ['AND/OR/NOT logic, latching, interlocks','Timers and counters (introduction)']},{section: 'Addressing & Signals',topics: ['Digital inputs/outputs concepts','Introduction to tags and documentation']},{section: 'Intro Troubleshooting',topics: ['Common wiring/logic mistakes','Basic fault-finding mindset']}],
    practical_labs: ['Build simple start/stop circuits','Implement interlocks and timer-based control','Create basic counter applications'],
    certification: 'Certificate of Completion awarded upon successful participation in the course.',
    upcoming_sessions: ['19–23 Jan 2026','13–17 Apr 2026'],
  },
  {
    slug: 's7-service-maintenance-part-1',
    title: 'S7 Service & Maintenance Course Part 1',
    level: 'Intermediate',
    category: 'Maintenance',
    platform: 'S7 Classic (STEP 7 / SIMATIC Manager)',
    duration: '5 days',
    prerequisites: 'Introduction to Programmable Controllers course or equivalent experience',
    summary: 'Learn essential maintenance skills for Siemens S7 PLCs using SIMATIC Manager. Master hardware identification, diagnostics, backup/restore procedures, and module replacement.',
    who_its_for: 'Maintenance technicians, electricians, and engineers responsible for maintaining Siemens S7 Classic PLC systems in industrial environments.',
    outcomes: ['Identify S7 hardware components including CPU, PS, DI/DO, AI/AO modules','Navigate SIMATIC Manager project structure and blocks','Perform upload/download operations safely','Interpret LED indications and diagnostic buffers','Monitor variables and apply safe forcing practices','Execute backup/restore and archiving procedures'],
    syllabus: [{section: 'Hardware Identification',topics: ['CPU, PS, DI/DO, AI/AO modules overview','Basic installation & wiring checks']},{section: 'SIMATIC Manager Essentials',topics: ['Project structure, blocks overview (OB/FB/FC/DB)','Upload/download basics']},{section: 'Diagnostics',topics: ['LED indications, diagnostic buffers','Basic online monitoring and variable forcing (safe practices)']},{section: 'Maintenance Workflow',topics: ['Backup/restore, archiving projects','Replacing modules and verifying addresses']}],
    practical_labs: ['Diagnose common faults using SIMATIC Manager','Replace modules in a simulated scenario','Perform safe backup and restore operations'],
    certification: 'Certificate of Completion awarded upon successful participation in the course.',
    upcoming_sessions: ['02–06 Feb 2026','04–08 May 2026'],
  },
  {
    slug: 'tia-portal-service-maintenance-part-1',
    title: 'TIA Portal Service & Maintenance Course Part 1',
    level: 'Intermediate',
    category: 'Maintenance',
    platform: 'TIA Portal',
    duration: '5 days',
    prerequisites: 'Introduction to Programmable Controllers or equivalent',
    summary: 'Essential maintenance skills for Siemens S7-1200/1500 PLCs using TIA Portal. Learn project navigation, hardware configuration, online diagnostics, and backup procedures.',
    who_its_for: 'Maintenance technicians and engineers responsible for TIA Portal-based automation systems. Ideal for those transitioning from S7 Classic.',
    outcomes: ['Navigate TIA Portal project structure efficiently','Configure hardware using the hardware catalog','Perform upload/download and project backup routines','Use online diagnostics and watch tables','Apply safe monitoring and forcing practices','Execute backup, archiving, and restoration procedures'],
    syllabus: [{section: 'TIA Portal Project Structure',topics: ['Devices & networks, project navigation','Upload/download & project backup routines']},{section: 'Hardware Configuration',topics: ['Hardware catalog, rack/device configuration','Addressing of signal modules','CPU properties overview']},{section: 'Online Tools',topics: ['Online & diagnostics, watch tables','Monitoring and safe forcing practices']},{section: 'Maintenance Best Practice',topics: ['Backups, archiving, restoration procedures']}],
    practical_labs: ['Diagnose faults using TIA diagnostics','Backup and restore projects','Replace device configuration'],
    certification: 'Certificate of Completion awarded upon successful participation in the course.',
    upcoming_sessions: ['16–20 Feb 2026','11–15 Mar 2026','06–10 Apr 2026'],
  },
  {
    slug: 'tia-portal-programming-part-1',
    title: 'TIA Portal Programming – Part 1',
    level: 'Intermediate',
    category: 'Programming',
    platform: 'TIA Portal (S7-1200/1500)',
    duration: '5 days',
    prerequisites: 'Introduction to Programmable Controllers',
    summary: 'Learn to program Siemens S7-1200/1500 PLCs using TIA Portal. Master symbolic programming, block organisation, and commissioning workflows.',
    who_its_for: 'Engineers and technicians who need to develop TIA Portal programs from scratch. Ideal for those moving from S7 Classic or new to Siemens programming.',
    outcomes: ['Translate process requirements into TIA project structure','Create and manage tag tables with proper naming conventions','Organise programs using OB/FB/FC/DB blocks','Write clean logic in LAD and FBD','Commission programs using monitoring and debugging tools','Apply consistent documentation practices'],
    syllabus: [{section: 'From Process to Project',topics: ['Translating process requirements into TIA structure']},{section: 'Tags and Symbolic Programming',topics: ['Tag tables, naming conventions, documentation']},{section: 'OB/FB/FC/DB in TIA',topics: ['Program organisation and best practices']},{section: 'LAD/FBD Basics',topics: ['Core logic patterns and readability']},{section: 'Commissioning',topics: ['Monitoring, modifying variables, debugging workflow']}],
    practical_labs: ['Build a machine logic project with structured tags','Implement basic sequences','Execute commissioning steps'],
    certification: 'Certificate of Completion awarded upon successful participation in the course.',
    upcoming_sessions: ['26–30 Jan 2026','16–20 Feb 2026','18–22 Mar 2026','20–24 Apr 2026'],
  },
  {
    slug: 'tia-portal-programming-part-2',
    title: 'TIA Portal Programming – Part 2',
    level: 'Advanced',
    category: 'Programming',
    platform: 'TIA Portal',
    duration: '5 days',
    prerequisites: 'TIA Portal Programming – Part 1',
    summary: 'Advanced TIA Portal programming including modular FB design, advanced instructions, debugging strategies, and professional documentation.',
    who_its_for: 'Programmers who have completed Part 1 and want to develop scalable, professional-grade TIA Portal applications.',
    outcomes: ['Design modular FB structures with clean interfaces','Create reusable, scalable code for real machines','Use advanced instructions including edge detection and number formats','Apply systematic debugging methodologies','Manage project consistency and version control','Prepare comprehensive handover documentation'],
    syllabus: [{section: 'Structured Programming',topics: ['Modular FB design, clean interfaces','Reuse and scaling for real machines']},{section: 'Advanced Instructions',topics: ['Edge detection, timers/counters, number formats','Data handling and conversion concepts']},{section: 'Debugging & Optimisation',topics: ['Troubleshooting methodology','Safer changes while commissioning']},{section: 'Documentation & Archiving',topics: ['Project consistency, backups, exporting, handover preparation']}],
    practical_labs: ['Extend Part 1 project to modular FB-based architecture','Implement fault diagnostics','Create handover documentation package'],
    certification: 'Certificate of Completion awarded upon successful participation in the course.',
    upcoming_sessions: ['23–27 Feb 2026','13–17 Mar 2026','22–26 Apr 2026','25–29 May 2026'],
  },
  {
    slug: 'tia-portal-distributed-safety',
    title: 'TIA Portal Distributed Safety Course',
    level: 'Advanced',
    category: 'Safety',
    platform: 'TIA Portal Safety',
    duration: '5 days',
    prerequisites: 'TIA Portal Programming + safety basics recommended',
    summary: 'Implement functional safety solutions using TIA Portal. Learn safety programming, configuration, and validation practices.',
    who_its_for: 'Automation engineers and safety specialists who need to design and commission safety functions using Siemens safety PLCs.',
    outcomes: ['Understand safety lifecycle concepts','Configure safety CPUs and devices in TIA Portal','Structure safety programs correctly','Implement safety interlocks and acknowledgements','Apply basic validation and testing workflows','Document safety functions appropriately'],
    syllabus: [{section: 'Safety Fundamentals',topics: ['Safety lifecycle concept, safe stop principles (high level)']},{section: 'TIA Safety Configuration',topics: ['Safety CPU/device concepts, safety program structure']},{section: 'Safety Programming',topics: ['Safety blocks, safety interlocks, acknowledgement concepts']},{section: 'Testing and Validation',topics: ['Documentation and basic validation workflow (high level)']}],
    practical_labs: ['Configure an e-stop or guard safety function','Validate safety operation in controlled environment','Create safety documentation'],
    certification: 'Certificate of Completion awarded upon successful participation in the course.',
    upcoming_sessions: ['02–06 Mar 2026','27 Apr–01 May 2026'],
  },
  {
    slug: 'tia-portal-wincc-hmi',
    title: 'TIA Portal WinCC HMI (Operator Panels)',
    level: 'Intermediate',
    category: 'HMI/SCADA',
    platform: 'TIA Portal WinCC',
    duration: '3 days',
    prerequisites: 'TIA Portal basics',
    summary: 'Create professional operator interfaces using TIA Portal WinCC. Master integrated HMI development with alarms, trends, and security.',
    who_its_for: 'TIA Portal users who need to design and implement HMI solutions as part of integrated automation projects.',
    outcomes: ['Set up HMI devices and PLC connections in TIA Portal','Design consistent screen layouts and navigation','Integrate PLC tags efficiently','Configure alarm classes and acknowledgement','Implement trending and logging','Apply basic security concepts'],
    syllabus: [{section: 'HMI Engineering in TIA',topics: ['HMI device setup, PLC connection']},{section: 'Tags and Screens',topics: ['Tag integration, screen navigation, layout best practices']},{section: 'Alarms and Trends',topics: ['Alarm classes, acknowledgement, trends logging concepts']},{section: 'Operator Experience',topics: ['Usability, consistent styles, basic security concepts']}],
    practical_labs: ['Create an operator panel interface for a small machine','Implement alarms and trends','Test operator workflows'],
    certification: 'Certificate of Completion awarded upon successful participation in the course.',
    upcoming_sessions: ['07–09 Feb 2026','11–13 Mar 2026','13–15 Apr 2026'],
  },
];

export const getCourseBySlug = (slug) => courses.find(c => c.slug === slug);

export const getFilteredCourses = (filters) => {
  return courses.filter(course => {
    if (filters.level && filters.level !== 'all' && course.level !== filters.level) return false;
    if (filters.category && filters.category !== 'all' && course.category !== filters.category) return false;
    if (filters.platform && filters.platform !== 'all' && !course.platform.toLowerCase().includes(filters.platform.toLowerCase())) return false;
    return true;
  });
};

export const categories = [...new Set(courses.map(c => c.category))];
export const levels = [...new Set(courses.map(c => c.level))];
export const platforms = ['S7 Classic', 'TIA Portal', 'WinCC', 'SIMATIC NET', 'Safety', 'Drives'];
